src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Year__c</fullName>
        <label>Current Year</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Exam_Fees_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exam Fees Submitted ?</label>


        <length>7</length>
        <required>true</required>

        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Father_Mobile_Number__c</fullName>
        <label>Father Mobile Number</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fees_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fees Submitted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <label>Home Phone</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pending_Exam_Fees__c</fullName>
        <label>Pending Exam Fees</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pending_Fees_Amount__c</fullName>
        <label>Pending Fees Amount</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Roll_Number__c</fullName>
        <label>Roll Number</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stream__c</fullName>
        <label>Stream</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Student_Data.cls
public class Student_Data {
    public Student_Data(){
        //Insreting the details of student
        Student__c s1=new Student__c();
        s1.name='XYZ';
        s1.Roll_Number__c=98765;
        s1.Address__c='Uttar-Pradesh';
        s1.Email_Address__c='sks@fexle.com';
        s1.Father_Mobile_Number__c=1212121212;
		s1.Address__c='Bareilly_Uttar-Pradesh';
        s1.Home_Phone__c=1212121212;
        //Class Info:
        s1.Stream__c='CSE';
        s1.Section__c='B';
        //Fees Details:
        s1.Current_Year__c=4;
        s1.Fees_Submitted__c='Yes';
        s1.Pending_Exam_Fees__c=0;
        s1.Exam_Fees_Submitted__c='Yes';
        s1.Pending_Fees_Amount__c=00; 
        insert s1;
        //Querry for 5 students
        List<Student__c> stuList=[select name,Roll_Number__c,Address__c,Email_Address__c from Student__c order by createdDate DESC LIMIT 5];
        for(Student__c student:stuList){
            system.debug('Analyze Student_Data:-->'+student);
        }
         
    } 
}