src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Current_Year__c</fullName>
        <label>Current Year</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stream__c</fullName>
        <label>Stream</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject_in_which_Back__c</fullName>
        <label>Subject in which Back</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X4rh_sem_percentage__c</fullName>
        <label>4rh sem percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X4rth_sem_back__c</fullName>
        <defaultValue>false</defaultValue>
        <label>4rth sem back ?</label>
        <type>Checkbox</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Teacher_Layout_Data.cls
public class Teacher_Layout_Data {
    public Teacher_Layout_Data(){
        Student__c s3=new Student__c();
        //insert data
        s3.Current_Year__c=2022;
        s3.Stream__c='CSE';
        s3.Subject_in_which_Back__c='none';
        s3.X1st_Sem_back__c=False;
        s3.X1st_Sem_Percentage__c=80;
        s3.X2nd_Sem_Back__c=False;
        s3.X2nd_Sem_Percentage__c=82;
        s3.X3rd_Sem_Back__c=False;
        s3.X3rd_Sem_Percentage__c=84;
        s3.X4rth_sem_back__c=False;
        s3.X4rh_sem_percentage__c=89;
         insert s3;
        system.debug('Record Data:'+s3.id);
    }
    
    
}